### ISSUE TITLE
implement cookie and authentication 

### ISSUE THREAD

**Issue by katlukens** [ddbgio/nailivic#7]
## todo
replace default login success with actual check against DB, generating and presenting token cookie to client

## resources
- https://www.alexedwards.net/blog/working-with-cookies-in-go
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
- https://firefox-source-docs.mozilla.org/devtools-user/storage_inspector/index.html

**Comment by turkosaurus** [comment]
completed by package: https://github.com/ddbgio/cookie
